services:
  web:
    build: .
    image: memopyk-site:latest
    ports:
      - "3000:3000"           # map container → host port
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3
    restart: always